services:
  - type: web
    name: mental-health-chatbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PINECONE_API
        value: pcsk_BUbYK_Pyudx3Gerwnm5nqrrfwisv4D5tbqnsxZnqrXWrE1zYBzohG8z2hDbjKJqsAZGzz
      - key: GEMINI_API
        value: AIzaSyCTyXXx0qZ6IzFNCJsU0W_DK3MJngsYudA
      - key: SERPAPI_API
        value: 51bf1cded96c34b5bba5c63ac22961b36ebbad101281986be58406b940a8a893